name: python-demo

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
    env:
      JF_URL: ${{ secrets.JF_URL }}
      JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}
      MODULE_NAME: "jfrog-python-example"
      SERVER_ID: "rtsaas"
      REPO: "auth-python-virtual"
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Setup JFrog CLI 
        uses: jfrog/setup-jfrog-cli@v3.4.0
      - name: JFrog CLI config
        run: jf c add $SERVER_ID --url=$JF_URL --access-token=$JF_ACCESS_TOKEN --interactive=false
      - name: Ping JFrog CLI
        run: jf rt ping --server-id=$SERVER_ID
      - name: Run Python build and publish
        run: |
          jf pipc --server-id-resolve=$SERVER_ID --repo-resolve=$REPO
          # Build the python project
          jf pip install -r requirements.txt --module=$MODULE_NAME 
          # Package the project, create distribution archives (tar.gz and whl):
          python3 setup.py sdist bdist_wheel
      - name: Publish build
        run: |
           # Collect and store environment variables in the build-info
           jfrog rt bce
           # Collect and store VCS details in the build-info
           jfrog rt bag
           # Publish the build-info to Artifactory
           jfrog rt bp
           # Scan the published build-info with Xray
           jfrog rt bs 
        if: always()
