name: python-demo

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      JF_ARTIFACTORY_1: ${{ secrets.JF_ARTIFACTORY_SECRET_1 }}
      MODULE_NAME: "jfrog-python-example"
      SERVER_ID: "rtsaas"
      REPO: "auth-python-virtual"
    steps:
      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v3.4.0
      - name: Run Python build
        run: |
          jf pipc --server-id-resolve=$SERVER_ID --repo-resolve=$REPO
          
